import test from 'node:test';import assert from 'node:assert/strict';
import {observe,snapshot,fingerprint,codexArgs} from '../skills/relaynote/scripts/lib/feedback.mjs';
const empty={current_round:1,latest_review:null,open_comments:[],forms:[],tables:[]};
const decision={...empty,latest_review:{id:'decision-1',round:1,decision:'approved'}};
function setup(values,options={}){let state=null,index=0,events=[];const abort=new AbortController();return {events,abort,run:()=>observe({sessionId:'test',events:'feedback',getReview:async()=>{const v=values[Math.min(index++,values.length-1)];if(v instanceof Error)throw v;return v},deliver:async e=>events.push(e),loadState:async()=>state,saveState:async v=>{state=v},wait:async()=>{if(index>=values.length)abort.abort()},signal:abort.signal,...options})}}
test('long idle/reconnect needs no model and decision is delivered once',async()=>{const x=setup([empty,new Error('network'),empty,decision]);await x.run();assert.equal(x.events.length,1);assert.equal(x.events[0].feedback.decision.decision,'approved')});
test('comment edits and a later decision reach the same listener; unchanged polls do not',async()=>{const comment={...empty,open_comments:[{id:'c',body:'fix'}]};const edited={...comment,open_comments:[{id:'c',body:'fix please'}]};const x=setup([empty,comment,comment,edited,decision,decision],{continuous:true});await x.run();assert.equal(x.events.length,3)});
test('an empty new AI round is not feedback',async()=>{const x=setup([empty,{...empty,current_round:2}],{continuous:true});await x.run();assert.equal(x.events.length,0)});
test('delivery error stops without committing the cursor or launching replacements',async()=>{let saved=false;const x=setup([decision],{deliver:async()=>{throw new Error('origin unavailable')},saveState:async()=>{saved=true}});await assert.rejects(x.run(),/origin unavailable/);assert.equal(saved,false)});
test('persisted cursor prevents a restart from replaying the same decision',async()=>{const s=snapshot(decision,'feedback');const x=setup([decision],{loadState:async()=>({round:1,hash:fingerprint(s)})});await x.run();assert.equal(x.events.length,0)});
test('Codex only targets exact existing UUID via queue, with no shell interpretation',()=>{const thread='12345678-1234-1234-1234-123456789abc';assert.deepEqual(codexArgs(thread,'$(touch /tmp/no)'),['queue','--thread',thread,'--message','$(touch /tmp/no)']);assert.throws(()=>codexArgs('--last','x'));assert.throws(()=>codexArgs(thread,'x','wss://unknown.example'))});
test('authentication failures terminate rather than retrying forever',async()=>{class AuthError extends Error{};const x=setup([new AuthError('Reconnect')]);await assert.rejects(x.run(),/Reconnect/)});
