import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
const root=await fs.mkdtemp(path.join(os.tmpdir(),'relaynote-unit-'));
process.env.RELAYNOTE_HOME=path.join(root,'state');
const state=await import('../skills/relaynote/scripts/lib/state.mjs');
const{executeJob,agentCommand,armNext}=await import('../skills/relaynote/scripts/lib/daemon.mjs');
const{getReview,waitReview}=await import('../skills/relaynote/scripts/lib/mcp.mjs');
await state.init();
const bin=path.join(root,'bin');await fs.mkdir(bin);const oldPath=process.env.PATH;process.env.PATH=bin+path.delimiter+oldPath;
await fs.writeFile(path.join(bin,'codex'),`#!${process.execPath}\nimport fs from 'node:fs';let s='';for await(const b of process.stdin)s+=b;fs.appendFileSync(process.env.RELAYNOTE_HOME+'/calls',JSON.stringify({args:process.argv.slice(2),prompt:s,cwd:process.cwd()})+'\\n');`,{mode:0o700});
const result={session_id:'11111111-1111-4111-8111-111111111111',current_round:1,latest_review:{id:'decision-one',round:1,decision:'changes_requested',note:'Fix the label'}};
let response=result,status=200,sse=false;
const server=http.createServer(async(req,res)=>{let body='';for await(const c of req)body+=c;assert.equal(req.headers.authorization,'Bearer local-test-key');const message=JSON.parse(body);res.writeHead(status,{'Content-Type':sse?'text/event-stream':'application/json'});const data=JSON.stringify({jsonrpc:'2.0',id:message.id,result:{structuredContent:response}});res.end(sse?`event: message\ndata: ${data}\n\n`:data)});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
await state.write(path.join(state.home,'auth.json'),{base,apiKey:'local-test-key'});
const job=(id,status='waiting')=>({id:id.repeat(32),status,cwd:root,task:'Only fix the label. No commits or deployments.',agent:'codex',sessionId:result.session_id,round:1});
test.after(async()=>{process.env.PATH=oldPath;server.closeAllConnections();await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true})});
test('credentials remain owner-only and non-HTTPS remote origins are refused',async()=>{assert.equal((await fs.stat(path.join(state.home,'auth.json'))).mode&0o777,0o600);assert.throws(()=>state.endpoint('http://example.com'));assert.throws(()=>state.endpoint('https://user:password@example.com'));assert.throws(()=>state.jobPath('../outside'))});
test('JSON and SSE MCP results both work, old rounds do not fire',async()=>{assert.equal((await getReview(result.session_id)).latest_review.id,'decision-one');sse=true;assert.equal((await waitReview(result.session_id,1)).latest_review.decision,'changes_requested');await assert.rejects(waitReview(result.session_id,2),/ROUND_CHANGED/);sse=false;status=401;await assert.rejects(getReview(result.session_id),/Access denied/);status=200});
test('a decision launches exactly one subprocess without shell interpolation',async()=>{const j=job('a');await state.write(state.jobPath(j.id),j);await executeJob(j,result);await executeJob(j,result);assert.equal((await state.read(state.jobPath(j.id))).status,'completed');const lines=(await fs.readFile(path.join(state.home,'calls'),'utf8')).trim().split('\n');assert.equal(lines.length,1);const call=JSON.parse(lines[0]);assert.deepEqual(call.args,['exec','--json','-']);assert(call.prompt.includes('Fix the label'));assert(!call.prompt.includes('local-test-key'));assert.equal(call.cwd,await fs.realpath(root));});
test('stopped jobs do not dispatch and unsupported adapters fail explicitly',async()=>{const j=job('b','stopped');await state.write(state.jobPath(j.id),j);await executeJob(j,result);assert.equal((await state.read(state.jobPath(j.id))).status,'stopped');assert.throws(()=>agentCommand('cursor'),/supports/);assert.deepEqual(agentCommand('claude-code'),['claude',['-p','--output-format','json']]);});
test('nonzero agent exit is retained for inspection and never automatically repeated',async()=>{await fs.writeFile(path.join(bin,'claude'),'#!/bin/sh\nexit 7\n',{mode:0o700});const j={...job('c'),agent:'claude-code'};await state.write(state.jobPath(j.id),j);await executeJob(j,result);const failed=await state.read(state.jobPath(j.id));assert.equal(failed.status,'failed');assert.equal(failed.exitCode,7);await executeJob(j,result);assert.deepEqual(await state.read(state.jobPath(j.id)),failed);});

test('a revision arms the next round once, and follow-up chains are bounded',async()=>{const j={...job('d','completed'),base,follow:true,followPending:true,depth:0,expiresAt:Date.now()+60000};await state.write(state.jobPath(j.id),j);response={...result,current_round:2,review_status:'in_review',latest_review:null};await armNext(j);const saved=await state.read(state.jobPath(j.id));assert(saved.nextJobId);const next=await state.read(state.jobPath(saved.nextJobId));assert.equal(next.round,2);assert.equal(next.status,'waiting');assert.equal(next.task,j.task);await armNext(j);assert.equal((await state.jobs()).filter(x=>x.round===2).length,1);const limited={...job('e','completed'),follow:true,followPending:true,depth:9,expiresAt:Date.now()+60000};await state.write(state.jobPath(limited.id),limited);await armNext(limited);assert.equal((await state.read(state.jobPath(limited.id))).followPending,false);response=result;});
